### ISSUE TITLE
Installing the addon

### ISSUE THREAD

**Issue by IamTirion** [Mustard2/MustardTools#7]
Hello, I just want to ask, is this "addon" supposed to be installed by running the python script like installing MustardUI before it became an addon?

**Comment by Mustard2** [comment]
Since it's a single file addon, you can either run it as a script (and therefore it will be available only until you close Blender), or as an addon installing the .py file (not the zip!) in the Blender settings.

In both cases, the addon should work fine. :)

Did you encounter any issue?

**Comment by IamTirion** [comment]
Oh I just didn't know I could install a .py file. All the other addons come in a zip file. Well, now I have it as an addon. Thanks.

**Comment by Mustard2** [comment]
You're welcome! :)
