### ISSUE TITLE
Error key "MustardUI" not found on blender-4.2.0-alpha+main.38fcaf9ab93f-windows.amd64-release.

### ISSUE THREAD

**Issue by catafest** [Mustard2/MustardTools#9]
Good source code and tools for Mustard ... 
I get this error on blender-4.2.0-alpha+main.38fcaf9ab93f-windows.amd64-release
![image](https://github.com/Mustard2/MustardTools/assets/2210118/07013c88-7661-42ea-b7cb-b619d7404086)

**Comment by Mustard2** [comment]
Seems like an error in the installation. Always install the add-on downloading the package from the release pages: 

https://github.com/Mustard2/MustardTools/releases
https://github.com/Mustard2/MustardUI/releases
https://github.com/Mustard2/MustardSimplify/releases

That is, downloading from the main GitHub page of the project messes up with the file names, ending in this particular error.

Let me know if this fixes your error! :)
